server:
  port: 8070
eureka:
  instance:
    hostname: eurekaserver
  client:
    registerWithEureka: false #config 서버가 유레카 서비스에 등록되지 않도록 지시
    fetchRegistry: false #config 서버가 캐시 레지스트리 정보를 로컬에 캐시하지 않도록 지시
    serviceUrl:
      defaultZone: #서비스 URL 제공
        http://${eureka.instance.hostname}:${server.port}/eureka/

  server:
    waitTimeInMsWhenSyncEmpty: #서버가 요청을 받기 전 초기 대기 시간을 설정